### ISSUE TITLE
permission denied with new Lock object

### ISSUE THREAD

**Issue by dguibert** [flatironinstitute/nixpack#40]
In Spack commit https://github.com/spack/spack/commit/53ae969aa008c8fb358f33b9b961beb5512999ff (introduced by PR https://github.com/spack/spack/pull/33495), Lock objects can now be instantiated independently.

But this breaks nixpack with errors like:
````sh
spack-repo.nix> Generating package repo for myrepo, builtin...
spack-repo.nix> Traceback (most recent call last):
spack-repo.nix>   File "/nix/store/cd8rpf921g2wnzwjahliivbpjmhygbkf-source/lib/spack/llnl/util/lang.py", line 191, in _memoized_function
spack-repo.nix>     return func.cache[key]
spack-repo.nix> KeyError: (<spack.repo.RepoPath object at 0x7ffff6181480>, False)
spack-repo.nix> During handling of the above exception, another exception occurred:
spack-repo.nix> Traceback (most recent call last):
spack-repo.nix>   File "/nix/store/yq9i74c9x1yraz6prdbl4r9vvbkirvj4-generate.py", line 304, in <module>
spack-repo.nix>     for p in spack.repo.path.all_package_classes():
spack-repo.nix>   File "/nix/store/cd8rpf921g2wnzwjahliivbpjmhygbkf-source/lib/spack/spack/repo.py", line 754, in all_package_classes
spack-repo.nix>     for name in self.all_package_names():
spack-repo.nix>   File "/nix/store/cd8rpf921g2wnzwjahliivbpjmhygbkf-source/lib/spack/spack/repo.py", line 737, in all_package_names
spack-repo.nix>     return self._all_package_names(include_virtuals)
spack-repo.nix>   File "/nix/store/cd8rpf921g2wnzwjahliivbpjmhygbkf-source/lib/spack/llnl/util/lang.py", line 193, in _memoized_function
spack-repo.nix>     ret = func(*args, **kwargs)
spack-repo.nix>   File "/nix/store/cd8rpf921g2wnzwjahliivbpjmhygbkf-source/lib/spack/spack/repo.py", line 732, in _all_package_names
spack-repo.nix>     for name in repo.all_package_names(include_virtuals):
spack-repo.nix>   File "/nix/store/cd8rpf921g2wnzwjahliivbpjmhygbkf-source/lib/spack/spack/repo.py", line 1151, in all_package_names
spack-repo.nix>     return [x for x in names if not self.is_virtual(x)]
spack-repo.nix>   File "/nix/store/cd8rpf921g2wnzwjahliivbpjmhygbkf-source/lib/spack/spack/repo.py", line 1151, in <listcomp>
spack-repo.nix>     return [x for x in names if not self.is_virtual(x)]
spack-repo.nix>   File "/nix/store/cd8rpf921g2wnzwjahliivbpjmhygbkf-source/lib/spack/spack/repo.py", line 1205, in is_virtual
spack-repo.nix>     return pkg_name in self.provider_index
spack-repo.nix>   File "/nix/store/cd8rpf921g2wnzwjahliivbpjmhygbkf-source/lib/spack/spack/repo.py", line 1096, in provider_index
spack-repo.nix>     return self.index["providers"]
spack-repo.nix>   File "/nix/store/cd8rpf921g2wnzwjahliivbpjmhygbkf-source/lib/spack/spack/repo.py", line 588, in __getitem__
spack-repo.nix>     self._build_all_indexes()
spack-repo.nix>   File "/nix/store/cd8rpf921g2wnzwjahliivbpjmhygbkf-source/lib/spack/spack/repo.py", line 601, in _build_all_indexes
spack-repo.nix>     self.indexes[name] = self._build_index(name, indexer)
spack-repo.nix>   File "/nix/store/cd8rpf921g2wnzwjahliivbpjmhygbkf-source/lib/spack/spack/repo.py", line 616, in _build_index
spack-repo.nix>     with self.cache.read_transaction(cache_filename) as f:
spack-repo.nix>   File "/nix/store/cd8rpf921g2wnzwjahliivbpjmhygbkf-source/lib/spack/llnl/util/lock.py", line 751, in __enter__
spack-repo.nix>     if self._enter() and self._acquire_fn:
spack-repo.nix>   File "/nix/store/cd8rpf921g2wnzwjahliivbpjmhygbkf-source/lib/spack/llnl/util/lock.py", line 790, in _enter
spack-repo.nix>     return self._lock.acquire_read(self._timeout)
spack-repo.nix>   File "/nix/store/cd8rpf921g2wnzwjahliivbpjmhygbkf-source/lib/spack/llnl/util/lock.py", line 479, in acquire_read
spack-repo.nix>     wait_time, nattempts = self._lock(LockType.READ, timeout=timeout)
spack-repo.nix>   File "/nix/store/cd8rpf921g2wnzwjahliivbpjmhygbkf-source/lib/spack/spack/util/lock.py", line 61, in _lock
spack-repo.nix>     return super()._lock(op, timeout)
spack-repo.nix>   File "/nix/store/cd8rpf921g2wnzwjahliivbpjmhygbkf-source/lib/spack/llnl/util/lock.py", line 330, in _lock
spack-repo.nix>     self._file = FILE_TRACKER.get_fh(self.path)
spack-repo.nix>   File "/nix/store/cd8rpf921g2wnzwjahliivbpjmhygbkf-source/lib/spack/llnl/util/lock.py", line 129, in get_fh
spack-repo.nix>     fd = os.open(path, os_mode)
spack-repo.nix> PermissionError: [Errno 13] Permission denied: '/dev/shm/nix-build-spack-repo.nix.drv-0/spack-cache/providers/.myrepo-index.json.lock'
````

**Comment by dylex** [comment]
I see some references to `config:locks`. Does that work just to disable locks entirely? They theoretically shouldn't be needed with nixpack.

**Comment by dguibert** [comment]
Yes, see https://github.com/dguibert/spack/tree/dg/restore-config-locks (last 2 commits), don't hesitate to comment

I'll do a PR to spack (tomorrow).

**Comment by dguibert** [comment]
Hi @lgarrison,
I've just saw aeaed2a1891da1eb70dda75bda421f6fa73cce32, does it solve this issue?

**Comment by lgarrison** [comment]
It seems to sidestep the lock issue for the moment, although I have no idea if I set the config in the right place(s). @dylex will have to chime in on that. We haven't fixed the database path issue yet; working on that next.

**Comment by dguibert** [comment]
> It seems to sidestep the lock issue for the moment, although I have no idea if I set the config in the right place(s). @dylex will have to chime in on that. We haven't fixed the database path issue yet; working on that next.

Have you looked at https://github.com/spack/spack/pull/39356 where I solved both issues (locks and database path)?
I'm not sure if it can be solved within nixpack without modifying spack.

**Comment by lgarrison** [comment]
Yes, many thanks for opening that PR! https://github.com/flatironinstitute/nixpack/commit/aeaed2a1891da1eb70dda75bda421f6fa73cce32 only works because I merged that PR into our Spack fork. Hopefully it will be adopted upstream soon.

**Comment by dguibert** [comment]
> It seems to sidestep the lock issue for the moment, although I have no idea if I set the config in the right place(s). @dylex will have to chime in on that. We haven't fixed the database path issue yet; working on that next.

I've just understood your comment as I was kind of playing with `git-bisect` to find why spack wasn't using curl anymore (required on my system).

You could try this patch (I'm still testing it) but `spack.config.command_line_scopes` has been capitalized as well.
````diff
diff --git a/spack/cache.py b/spack/cache.py
index f1f3484ae9..8dbf27b46f 100644
--- a/spack/cache.py
+++ b/spack/cache.py
@@ -4,7 +4,6 @@ import os
 import nixpack
 import spack
 
-spack.config.set('config:locks', False, 'command_line')
 spack.config.set('config:misc_cache', os.environ['out'], 'command_line')
 print("Prepopulating spack repo cache...")
 spack.repo.PATH.all_package_names()
diff --git a/spack/modules.py b/spack/modules.py
index f09ce7e795..9395a4828a 100644
--- a/spack/modules.py
+++ b/spack/modules.py
@@ -179,7 +179,6 @@ config = {
         modtype: modconf
     }
 }
-spack.config.set('config:locks', False, 'command_line')
 spack.config.set('modules', config, 'command_line')
 spack.repo.PATH.provider_index # precompute
 
diff --git a/spack/nixpack.py b/spack/nixpack.py
index 8a6b3efc9f..f291e050ca 100644
--- a/spack/nixpack.py
+++ b/spack/nixpack.py
@@ -59,11 +59,10 @@ class NixStore():
     unpadded_root = spack.paths.prefix
 spack.store.store = NixStore()
 
-spack.config.command_line_scopes = getVar('spackConfig').split()
+spack.config.COMMAND_LINE_SCOPES = getVar('spackConfig').split()
 spack.config.CONFIG.remove_scope('system')
 spack.config.CONFIG.remove_scope('user')
 
-spack.config.set('config:locks', False, 'command_line')
 spack.config.set('config:build_stage', [getVar('NIX_BUILD_TOP')], 'command_line')
 enableParallelBuilding = bool(getVar('enableParallelBuilding', True))
 cores = 1
````

**Comment by dylex** [comment]
Oh, yes, I already put that fix (and another related one) on the spack-update-2023.08 branch last week -- sorry I didn't mention it here. We can probably merge that into main, though it would be nice to find a way to make this backwards compatible.
