### ISSUE TITLE
new "Index dependency metadata by `when` spec" breaks 'depends'

### ISSUE THREAD

**Issue by dguibert** [flatironinstitute/nixpack#45]
In https://github.com/spack/spack/commit/6542c94cc1e0cdb5f8c61936c78b74c46d7b6c01, the current dependency dictionary structure has been converted from this:

    { name: { when_spec: [Dependency ...] } }

to this:

    { when_spec: { name: [Dependency ...] } }
    
This breaks nixpack   
````
spack-repo.nix> + /home/bguibert/nix/store/jhrdz3rsaikgnz569my5zy7x84ggl7pn-python3-3.10.12/bin/python3 /home/bguibert/nix/store/0gvivkzyh5i2248f9lfxpnfbw062vdyi-generate.py
spack-repo.nix> Generating package repo for nixpack-pkgs, hpcw, bench, cbm2, builtin, builtin...
spack-repo.nix> Traceback (most recent call last):
spack-repo.nix>   File "/home/bguibert/nix/store/0gvivkzyh5i2248f9lfxpnfbw062vdyi-generate.py", line 357, in <module>
spack-repo.nix>     desc['depends'] = {n: depend(p, d) for n, d in p.dependencies.items()}
spack-repo.nix>   File "/home/bguibert/nix/store/0gvivkzyh5i2248f9lfxpnfbw062vdyi-generate.py", line 357, in <dictcomp>
spack-repo.nix>     desc['depends'] = {n: depend(p, d) for n, d in p.dependencies.items()}
spack-repo.nix>   File "/home/bguibert/nix/store/0gvivkzyh5i2248f9lfxpnfbw062vdyi-generate.py", line 321, in depend
spack-repo.nix>     c = [whenCondition(p, w, depPrefs(s), s) for w, s in sorted(d.items())]
spack-repo.nix>   File "/home/bguibert/nix/store/0gvivkzyh5i2248f9lfxpnfbw062vdyi-generate.py", line 321, in <listcomp>
spack-repo.nix>     c = [whenCondition(p, w, depPrefs(s), s) for w, s in sorted(d.items())]
spack-repo.nix>   File "/home/bguibert/nix/store/0gvivkzyh5i2248f9lfxpnfbw062vdyi-generate.py", line 272, in whenCondition
spack-repo.nix>     conditions(c, p, s, dep)
spack-repo.nix>   File "/home/bguibert/nix/store/0gvivkzyh5i2248f9lfxpnfbw062vdyi-generate.py", line 264, in conditions
spack-repo.nix>     if s.name is not None and s.name != p.name:
spack-repo.nix> AttributeError: 'str' object has no attribute 'name'
````

**Comment by dguibert** [comment]
The commit fixes this issue.

@dylex, can we close this?

**Comment by dylex** [comment]
Yeah, I don't really love this fix using `dependencies_by_name` because it's rather inefficient, but hopefully will get around to doing it better at some point.
